# Generated by Django 5.1.3 on 2024-11-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='_saldo',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, null=True),
        ),
    ]
